export {
	createDefineRelationRequestSchema,
	createGrantRelationRequestSchema,
	createRevokeRelationRequestSchema,
	createCheckRelationRequestSchema,
	createCheckPermissionRequestSchema,
	createListRelationsRequestSchema,
	createDeleteRelationRequestSchema,
	createGrantRelationToMultipleRequestSchema,
	createGetUserRelationsRequestSchema,
	createListRelationsResponseSchema,
	createResourceRelationSchema,
	createGetGroupRelationsResponseSchema,
	GroupMembershipRequestSchema,
	GetGroupMembersRequestSchema,
	GetGroupRelationsRequestSchema,
	RelationResultSchema,
	PermissionResultSchema,
	SuccessResponseSchema,
	ListGroupsResponseSchema,
	GetGroupMembersResponseSchema,
} from './schema';

export type {
	DefineRelationRequest,
	GrantRelationRequest,
	RevokeRelationRequest,
	CheckRelationRequest,
	CheckPermissionRequest,
	GroupMembershipRequest,
	ListRelationsRequest,
	DeleteRelationRequest,
	GetGroupMembersRequest,
	GetGroupRelationsRequest,
	GrantRelationToMultipleRequest,
	GetUserRelationsRequest,
	RelationResult,
	PermissionResult,
	SuccessResponse,
	ListRelationsResponse,
	ListGroupsResponse,
	GetGroupMembersResponse,
	ResourceRelation,
	GetGroupRelationsResponse,
	UserRelationEntry,
	GetUserRelationsResponse,
} from './schema';
